version: '3.3'

services:

  traefik:
    image: "traefik:v2.5"
    container_name: "rp_traefik"
    command:
     #- "--log.level=DEBUG"
      # Traefik will listen on port 8080 by default for API request.
      - "--api.insecure=true"
      # Enabling docker provider
      - "--providers.docker=true"
      # Do not expose containers unless explicitly told so
      - "--providers.docker.exposedbydefault=false"
      # Traefik will listen to incoming request on the port 80 (HTTP)
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: unless-stopped
  
  whoami:
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    container_name: rp_whoami
    labels:
      # Explicitly tell Traefik to expose this container
      - "traefik.enable=true"
      # The domain the service will respond to
      - "traefik.http.routers.whoami.rule=Host(`whoami.samio.live`)"
      # Allow request only from the predefined entry point named "web"
      - "traefik.http.routers.whoami.entrypoints=web"
    restart: unless-stopped

  vscode:
    image: lscr.io/linuxserver/code-server
    container_name: rp_vscode
    labels:
      # Explicitly tell Traefik to expose this container
      - "traefik.enable=true"
      # The domain the service will respond to
      - "traefik.http.routers.vscode.rule=Host(`vscode.samio.live`)"
      # Allow request only from the predefined entry point named "web"
      - "traefik.http.routers.vscode.entrypoints=web"
    volumes:
      # - .vscode/code-server:/root/.config/code-server
      # - .vscode/extensions:/root/.local/share/code-server/extensions
      - /home/teatonic/repos:/workspace
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - PASSWORD=${VSCODE_PASS} #optional
      # - FILE__PASSWORD=/home/teatonic/mysecretpassword
    user: 0:0 
    restart: unless-stopped

    
